name: SonarCloud PR Analysis

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout code
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2️⃣ Set up Node.js
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3️⃣ Install dependencies including coverage provider
      - name: Install dependencies
        run: |
          npm install
          npm install -D @vitest/coverage-v8

      # 4️⃣ Run tests with coverage
      - name: Run tests with coverage
        run: |
          npx vitest run --coverage --coverage.reporter=lcov || true

      # 5️⃣ Verify coverage file was created
      - name: Verify coverage file
        run: |
          ls -la coverage/
          if [ -f "coverage/lcov.info" ]; then
            echo "Coverage file exists"
            head -5 coverage/lcov.info
          else
            echo "Coverage file not found!"
            exit 1
          fi

      # 6️⃣ SonarCloud Scan
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=RADhaigude_react-test
            -Dsonar.organization=radhaigude
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
