name: QA / SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  sonarcloud-analysis:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout code
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # 2️⃣ Set up Node.js
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm install

      # 4️⃣ Add intentionally failing / uncovered code to trigger Quality Gate fail
      - name: Add failing/uncovered code
        run: |
          echo "function uncoveredFunc() { return 42 }" >> fail.js
          echo "function duplicateFunc() { return 1 }" >> fail.js

      # 5️⃣ Run tests with coverage (force continue even if fail)
      - name: Run tests
        run: npm test -- --coverage --coverageReporters=lcov || true

      # 6️⃣ Verify coverage file
      - name: Check coverage file
        run: |
          echo "Listing coverage directory:"
          ls -l coverage
          echo "First 10 lines of lcov.info:"
          head -n 10 coverage/lcov.info

      # 7️⃣ SonarCloud Scan
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=RADhaigude_react-test
            -Dsonar.organization=radhaigude
            -Dsonar.sources=.
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.exclusions="**/node_modules/**,**/*.test.js"
            -Dsonar.qualitygate.wait=true
            -Dsonar.branch.name=${{ github.head_ref || 'main' }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # 8️⃣ Quality Gate Check
      - name: Quality Gate Check
        uses: SonarSource/sonarcloud-quality-gate-action@v1.0.1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  cross-platform-test:
    name: Test Across OS
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run coverage & dump properties
        uses: ./ # this assumes you have a local action that supports args
        with:
          args: -Dsonar.scanner.internal.dumpToFile=./output.properties
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Assert coverage file created
        run: ./test/assertFileExists ./output.properties

