name: CI - Build, Test, SonarCloud

on:
  push:
    branches: [ main, dev, qa, master ]
  pull_request:
    branches: [ main, dev, qa ]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout repository
      - uses: actions/checkout@v4

      # 2️⃣ Setup .NET
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'

      # 3️⃣ Build & Test Backend
      - name: Build & Test Backend
        run: |
          cd backend
          dotnet restore
          dotnet build --configuration Release
          dotnet test --configuration Release --collect:"XPlat Code Coverage" --results-directory ./TestResults

      # 4️⃣ Upload Test Results
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: backend-test-results
          path: backend/TestResults

  frontend:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout repository
      - uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3️⃣ Build & Test Frontend
      - name: Build & Test Frontend
        run: |
          cd frontend
          npm install
          npm run test -- --watch=false --code-coverage

      # 4️⃣ Upload Coverage Report
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage
          path: frontend/coverage

  sonarcloud:
    runs-on: ubuntu-latest
    needs: [backend, frontend]
    steps:
      # 1️⃣ Checkout code
      - uses: actions/checkout@v4

      # 2️⃣ Setup Java (SonarScanner requires Java runtime)
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 3️⃣ Setup Node.js (if frontend reports are needed)
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      # 4️⃣ Prepare sonar-project.properties
      - name: Prepare SonarCloud properties
        run: |
          echo "sonar.organization=radhaigude" > sonar-project.properties
          echo "sonar.projectKey=RADhaigude_invoice-generator-react" >> sonar-project.properties
          echo "sonar.projectName=Invoice Generator React" >> sonar-project.properties
          echo "sonar.sources=frontend/src,backend" >> sonar-project.properties
          echo "sonar.sourceEncoding=UTF-8" >> sonar-project.properties
          echo "sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info" >> sonar-project.properties
          echo "sonar.cs.opencover.reportsPaths=backend/TestResults/**/coverage.opencover.xml" >> sonar-project.properties

      # 5️⃣ Install sonar-scanner
      - name: Install SonarScanner
        run: npm install -g sonar-scanner

      # 6️⃣ Run SonarCloud Analysis (with Quality Gate check)
      - name: Run SonarCloud scan
        run: |
          sonar-scanner \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      # 7️⃣ Check Quality Gate Result
      - name: SonarCloud Quality Gate
        uses: SonarSource/sonarqube-quality-gate-action@master
        with:
          sonarToken: ${{ secrets.SONAR_TOKEN }}
          sonarHostUrl: https://sonarcloud.io
