name: SonarCloud Check

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3️⃣ Install dependencies
      - run: npm install

      # 4️⃣ Run tests (Vitest or Jest)
      - run: npm run test -- --coverage

      # 5️⃣ Run SonarCloud Scan (official action)
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

