name: SonarCloud Scan

on:
  pull_request:
    branches: main
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - uses: actions/checkout@v3

      # 2️⃣ Set up Node.js
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm install

      # 4️⃣ Run tests with coverage
      - name: Run tests
        run: npm test -- --coverage --coverageReporters=lcov

      # 5️⃣ Debug coverage file
      - name: Check coverage file
        run: |
          echo "Listing coverage directory:"
          ls -l coverage
          echo "First 10 lines of lcov.info:"
          head -n 10 coverage/lcov.info

      # 6️⃣ SonarCloud code analysis
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.11
        with:
          projectKey: your_project_key         # Replace with your SonarCloud project key
          organization: your_organization     # Replace with your SonarCloud organization
          token: ${{ secrets.SONAR_TOKEN }}   # Make sure SONAR_TOKEN is added in GitHub Secrets
          args: >
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.exclusions="**/node_modules/**,**/*.test.js"

      # 7️⃣ Quality Gate check
      - name: Quality Gate Check
        uses: SonarSource/sonarcloud-quality-gate-action@v1

