name: SonarCloud PR Analysis

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - qa

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout code
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2️⃣ Set up Node.js
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm install

      # 4️⃣ Run tests and generate coverage
      - name: Run tests with coverage
        run: npm test -- --coverage --watchAll=false

      # 5️⃣ SonarCloud analysis
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}       # Default GitHub token
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   
